project_id = "agnyfrhzafvfsrbwdfpi"

[functions.get-finance-summary]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.create-subscription-checkout]
verify_jwt = true

[functions.check-subscription-status]  
verify_jwt = true

[functions.customer-portal]
verify_jwt = true