// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agnyfrhzafvfsrbwdfpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnbnlmcmh6YWZ2ZnNyYndkZnBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNjgzMDEsImV4cCI6MjA3MjY0NDMwMX0.zXZZTKPC_T5YW7OvCbuJhgtsXRwRfZfyYYKZ9nmXoD0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});